---
- src: git+https://github.com/dataiku/dataiku-api-client-python
  name: dataiku-api-client-python
  version: release/8.0
- src: git+https://github.com/dataiku/dataiku-ansible-modules
  name: dataiku-ansible-modules
  version: master