---
- src: git+https://github.com/dataiku/dataiku-api-client-python
  name: dataiku-api-client-python
  version: 12.1.0
- src: git+https://github.com/datarsense/dataiku-ansible-modules
  name: datarsense.dataiku-ansible-modules
  version: "20230919"
