---
# Default package manager in Centos 7 is YUM
- name: Installing sudo package
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - sudo
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '7'

- name: Enable EPEL Repository on CentOS 7
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: latest
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '7'
  tags: [molecule-idempotence-notest]

# Default package manager in Centos 8 is DNF
- name: Installing sudo package
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - sudo
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '8'

- name: Enable EPEL Repository on CentOS 8
  become: true
  ansible.builtin.dnf:
    name: epel-release
    state: latest
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '8'
  tags: [molecule-idempotence-notest]

- name: Installing dependencies
  become: true
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - acl
      - expat
      - git
      - nginx
      - unzip
      - zip
      - java-1.8.0-openjdk
      - freetype 
      - libgfortran 
      - libgomp
      - python3-setuptools

- name: Installing CentOS 7 specific packages
  become: true
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - libselinux-python
      - libselinux-python3
      - python3
      - python-setuptools
      - python-six
      - python-requests
      - python-dateutil
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '7'

- name: Installing CentOS 8 specific packages
  become: true
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ncurses-compat-libs
      - python3-libselinux
      - python2
      - python2-setuptools
      - python2-six
      - python2-requests
      - python36 
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '8'

- name: Set Python 3 as the default python interpreter
  become: true
  community.general.alternatives:
    name: python
    path: /usr/bin/python3
    link: /usr/bin/python
    state: selected

- name: Disable SELinux
  become: true
  when: "'selinux-policy' in ansible_facts.packages"
  ansible.posix.selinux:
    state: disabled
  register: selinuxdisabled
  notify:
    - Reboot server
  tags: [setup]