---
# Default package manager in Centos 7 is YUM
- name: Installing sudo package
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - sudo
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '7'

- name: Enable EPEL Repository on CentOS 7
  become: true
  yum:
    name: epel-release
    state: latest
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '7'

# Default package manager in Centos 8 is DNF
- name: Installing sudo package
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - sudo
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '8'

- name: Enable EPEL Repository on CentOS 8
  become: true
  dnf:
    name: epel-release
    state: latest
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '8'

- name: Installing dependencies
  become: true
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - acl
      - expat
      - git
      - nginx
      - unzip
      - zip
      - java-1.8.0-openjdk
      - freetype 
      - libgfortran 
      - libgomp
      - python3-setuptools
      - python-setuptools
      - python-six
      - python-requests
      - python-dateutil

- name: Installing CentOS 7 sepecific packages
  become: true
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python3
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '7'

- name: Installing CentOS 8 sepecific packages
  become: true
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ncurses-compat-libs
      - python2 
      - python36 
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '8'