- name: Configure LDAP settings
  when: configure_ldap_settings|bool
  dss_general_settings:
    connect_to: "{{ dss_connection_info }}"
    settings:
      ldapSettings:
        enabled: true
        url: "{{ ldap_url }}"
        bindDN: "{{ ldap_binddn }}"
        bindPassword: "{{ ldap_bindpassword }}"
        useTls: "{{ ldap_usetls }}"
        autoImportUsers: "{{ ldap_autoimportusers }}"
        userFilter: "{{ ldap_userfilter }}"
        defaultUserProfile: "{{ ldap_defaultuserprofile }}"
        displayNameAttribute: "{{ ldap_displaynameattribute }}"
        emailAttribute: "{{ ldap_emailattribute }}"
        enableGroups: "{{ ldap_enablegroups }}"
        groupFilter: "{{ ldap_groupfilter }}"
        groupNameAttribute: "{{ ldap_groupnameattribute }}"
        groupProfiles: "{{ ldap_groupprofiles }}"
        authorizedGroups: "{{ ldap_authorizedgroups }}"
  register: ldap_settings
  changed_when: "'MODIFIED' in ldap_settings.message"
  failed_when: ldap_settings.failed and ("'Your license does not allow you to enable LDAP authentication' not in ldap_settings.msg")
  ignore_errors: yes
  tags: [dss-authentication, molecule-idempotence-notest]

- name: Configure OIDC SSO settings
  when: configure_oidc_sso|bool
  dss_general_settings:
    connect_to: "{{ dss_connection_info }}"
    settings:
      ssoSettings:
        enabled: "{{ configure_oidc_sso }}"
        protocol: OPENID
        remappingRu1es: []
        openIDParams:
            clientId: "{{ oidc_clientid }}"
            clientSecret: "{{ oidc_clientsecret }}"
            scope: "{{ oidc_scope }}"
            issuer: "{{ oidc_issuer }}"
            authorizationEndpoint: "{{ oidc_authorizationendpoint }}"
            tokenEndpoint: "{{ oidc_tokenendpoint }}"
            jwksUri: "{{ oidc_jwksuri }}"
            claimKeyIdentifier: "{{ oidc_claimkeyidentifier }}"
            useGlobalProxy: true
            tokenEndpointAuthMethod: CLIENT_SECRET_BASIC
  register: oidc_sso_settings
  changed_when: "'MODIFIED' in oidc_sso_settings.message"
  tags: [dss-authentication, molecule-idempotence-notest]