---

- name: Retrieve API Credentials
  become: true
  become_user: "{{ dss_service_user }}"
  dss_get_credentials:
    datadir: "{{ dss_service_user_home_basedir }}/{{ dss_service_user }}/{{ dss_datadir }}"
    api_key_name: ansible
  register: dss_connection_info
  tags: [dss-config]

- name: Configure LDAP settings
  when: configure_ldap_settings|bool
  dss_general_settings:
    connect_to: "{{ dss_connection_info }}"
    settings:
      ldapSettings:
        enabled: true
        url: "{{ ldap_url }}"
        bindDN: "{{ ldap_binddn }}"
        bindPassword: "{{ ldap_bindpassword }}"
        useTls: "{{ ldap_usetls }}"
        autoImportUsers: "{{ ldap_autoimportusers }}"
        userFilter: "{{ ldap_userfilter }}"
        defaultUserProfile: "{{ ldap_defaultuserprofile }}"
        displayNameAttribute: "{{ ldap_displaynameattribute }}"
        emailAttribute: "{{ ldap_emailattribute }}"
        enableGroups: "{{ ldap_enablegroups }}"
        groupFilter: "{{ ldap_groupfilter }}"
        groupNameAttribute: "{{ ldap_groupnameattribute }}"
        groupProfiles: "{{ ldap_groupprofiles }}"
        authorizedGroups: "{{ ldap_authorizedgroups }}"
  register: ldapSettings
  changed_when: "'MODIFIED' in ldapSettings.message"
  failed_when: ("'FAILED' in command_result.stderr") and ("'Your license does not allow you to enable LDAP authentication' in command_result.stderr")
  tags: [dss-config]

- name: Configure containerized execution on Kubernetes in DSS settings
  when: configure_k8s
  dss_general_settings:
    connect_to: "{{ dss_connection_info }}"
    settings:
      containerSettings:
        executionConfigs: "{{ k8s_executionconfigs }}"
  register: containerSettings
  changed_when: "'MODIFIED' in containerSettings.message"
  tags: [dss-config]

- name: Enable spark support in DSS settings
  when: configure_spark
  dss_general_settings:
    connect_to: "{{ dss_connection_info }}"
    settings:
      sparkSettings:
        sparkEnabled: true
        executionConfigs: "{{ spark_executionconfigs }}"
  register: sparkSettings
  changed_when: "'MODIFIED' in sparkSettings.message"
  tags: [dss-config]

- name: Configure UIF user mappings
  when: configure_uif
  dss_general_settings:
    connect_to: "{{ dss_connection_info }}"
    settings:
      impersonation:
        userRules: "{{ uif_userrules }}"
  register: impersonationUserSettings
  changed_when: "'MODIFIED' in impersonationUserSettings.message"
  tags: [dss-config]

- name: Configure UIF group mappings
  when: configure_uif
  dss_general_settings:
    connect_to: "{{ dss_connection_info }}"
    settings:
      impersonation:
        groupRules: "{{ uif_grouprules }}"
  register: impersonationGroupSettings
  changed_when: "'MODIFIED' in impersonationGroupSettings.message"
  tags: [dss-config