---

- name: Retrieve API Credentials
  become: true
  become_user: "{{ dss_service_user }}"
  dss_get_credentials:
    datadir: "{{ dss_service_user_home_basedir }}/{{ dss_service_user }}/{{ dss_datadir }}"
    api_key_name: ansible
  register: dss_connection_info
  tags: [dss-config]

- name: Configure containerized execution on Kubernetes in DSS settings
  when: configure_k8s
  dss_general_settings:
    connect_to: "{{ dss_connection_info }}"
    settings:
      containerSettings:
        executionConfigs: "{{ k8s_executionconfigs }}"
  register: container_settings
  changed_when: "'MODIFIED' in container_settings.message"
  tags: [dss-config, molecule-idempotence-notest]

- name: Enable spark support in DSS settings
  when: configure_spark
  dss_general_settings:
    connect_to: "{{ dss_connection_info }}"
    settings:
      sparkSettings:
        sparkEnabled: true
        executionConfigs: "{{ spark_executionconfigs }}"
  register: spark_settings
  changed_when: "'MODIFIED' in spark_settings.message"
  tags: [dss-config, molecule-idempotence-notest]

- name: Configure UIF user mappings
  when: configure_uif
  dss_general_settings:
    connect_to: "{{ dss_connection_info }}"
    settings:
      impersonation:
        userRules: "{{ uif_userrules }}"
  register: impersonation_user_settings
  changed_when: "'MODIFIED' in impersonation_user_settings.message"
  tags: [dss-config, molecule-idempotence-notest]

- name: Configure UIF group mappings
  when: configure_uif
  dss_general_settings:
    connect_to: "{{ dss_connection_info }}"
    settings:
      impersonation:
        groupRules: "{{ uif_grouprules }}"
  register: impersonation_group_settings
  changed_when: "'MODIFIED' in impersonation_group_settings.message"
  tags: [dss-config, molecule-idempotence-notest]