---
- name: Download MySql JDBC connector
  when: configure_mysql and mysql_jdbc_connector_url is defined
  become: true
  become_user: "{{ dss_service_user }}"
  ansible.builtin.get_url:
    url: "{{ mysql_jdbc_connector_url }}"
    dest: "{{ dss_service_user_home_basedir }}/{{ dss_service_user }}/{{ dss_datadir }}/lib/jdbc/"
    mode: '644'
  notify:
    - Restart DSS
  tags: [setup, dss-setup]