---
# Check variables consistency before running tasks
- name: Check packages version consistency
  ansible.builtin.fail:
    msg: Hadoop or Spark package version does not match DSS version {{ dss_version }}
  when: (configure_spark) and (dss_hadoop_package is not search(dss_version) or dss_spark_package is not search(dss_version))

# Run role tasks
- name: PREPARE SERVER BEFORE DSS INSTALL
  ansible.builtin.import_tasks: pre_install.yml

- name: INSTALL or UPGRADE DSS
  ansible.builtin.import_tasks: install.yml

- name: CONGIGURE DSS
  ansible.builtin.import_tasks: config.yml
