---
# handlers file for ansible-role-dss

- name: Download Hadoop package
  become: true
  become_user: "{{ dss_service_user }}"
  ansible.builtin.get_url:
    url: "{{ dss_base_repository_url }}/{{ dss_version }}/{{ dss_hadoop_package }}"
    dest: "{{ dss_install_dir_location }}/{{ dss_hadoop_package }}"
    mode: '644'
  tags: [setup, dss-setup]

- name: Install or upgrade standalone Hadoop support
  become: true
  become_user: "{{ dss_service_user }}"
  ansible.builtin.command: "{{ dss_service_user_home_basedir }}/{{ dss_service_user }}/{{ dss_datadir }}/bin/dssadmin install-hadoop-integration -standaloneArchive {{ dss_install_dir_location }}/{{ dss_hadoop_package }}"
  tags: [dss]

- name: Download Spark package
  become: true
  become_user: "{{ dss_service_user }}"
  ansible.builtin.get_url:
    url: "{{ dss_base_repository_url }}/{{ dss_version }}/{{ dss_spark_package }}"
    dest: "{{ dss_install_dir_location }}/{{ dss_spark_package }}"
    mode: '644'
  tags: [setup, dss-setup]

- name: Install or upgrade standalone Spark support
  become: true
  become_user: "{{ dss_service_user }}"
  ansible.builtin.command: "{{ dss_service_user_home_basedir }}/{{ dss_service_user }}/{{ dss_datadir }}/bin/dssadmin install-spark-integration -standaloneArchive {{ dss_install_dir_location }}/{{ dss_spark_package }}{{ ' -forK8S' if configure_k8s }}"
  tags: [dss]

- name: Activate UIF
  become: true
  ansible.builtin.command: "{{ dss_service_user_home_basedir }}/{{ dss_service_user }}/{{ dss_datadir }}/bin/dssadmin install-impersonation {{ dss_service_user }}"
  tags: [dss]

- name: Read dss install id
  become: true
  become_user: "{{ dss_service_user }}"
  ansible.builtin.command: /bin/sh -c "grep installid {{ dss_service_user_home_basedir }}/{{ dss_service_user }}/{{ dss_datadir }}/install.ini | cut -d ' ' -f3" 
  register: dss_install_id
  changed_when: false
  tags: [dss]

- name: Deploy UIF configuration file
  become: true
  ansible.builtin.template: 
    src: "security-config.ini.j2"
    dest: "/etc/dataiku-security/{{ dss_install_id.stdout }}/security-config.ini"
    mode: 0644
  tags: [dss]

- name: Reboot server
  become: true
  ansible.builtin.reboot:
  tags: [setup]
