---
- name: Converge
  hosts: all
  tasks:
    - name: "Test DSS install"
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        dss_version: "10.0.7"
        configure_ldap_settings: "true"
    - name: "Test DSS upgrade"
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        dss_version: "11.1.1"
        configure_ldap_settings: "true"