---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: molecule-debian10
    image: docker.io/debian:buster
    pre_build_image: false
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  - name: molecule-almalinux8
    image: docker.io/almalinux:8.8
    pre_build_image: false
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: "/usr/sbin/init"
    tty: True
    env:
      container: docker
provisioner:
  name: ansible
  log: True
  env:
    ansible_python_interpreter: "/usr/bin/python3"
    DOCKER_TIMEOUT: 240
verifier:
  name: ansible
  env:
    ansible_python_interpreter: "/usr/bin/python3"