---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: molecule-debian10
    image: ${MOLECULE_IMAGE:-docker.io/debian:buster}
    pre_build_image: false
  - name: molecule-centos7
    image: ${MOLECULE_IMAGE:-docker.io/centos:7}
    pre_build_image: false
    privileged: true
    volumes: '/sys/fs/cgroup:/sys/fs/cgroup'
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_python_interpreter: "/usr/bin/python3"
verifier:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_python_interpreter: "/usr/bin/python3"

