---

- name: Copy docker base images build script
  become: true
  become_user: "{{ dss_service_user }}"
  ansible.builtin.template:
    src: "build_base_images.sh.j2"
    dest: "{{ dss_service_user_home_basedir }}/{{ dss_service_user }}/build_base_images.sh"
    mode: '700'
  register: docker_base_image_build_script
  when: (dataikudss_docker_build_base_image_mode == "build")
  tags: [docker-images]

- name: Test if DSS container-exec base image is registered locally
  become: true
  community.docker.docker_image_info:
    name:
      - "dku-exec-base-{{ dss_install_id.stdout.lower() }}:dss-{{ dss_version }}"
  register: result_test_container_exec_docker_image
  when: (dataikudss_docker_build_base_image_mode == "build")
  tags: [docker-images]
  
# A quick caveat about the folding > operator when used with ansible.builtin.shell: 
# the rows indented beneath it have to be at the same indentation level for the folding to happen correctly
- name: "Build docker container-exec base image"
  become: true
  become_user: "{{ dss_service_user }}"
  ansible.builtin.command: "{{ dss_service_user_home_basedir }}/{{ dss_service_user }}/build_base_images.sh container-exec"
  register: container_exec_image_build
  changed_when: "'INFO Done, cleaning up' in container_exec_image_build.msg"
  when: (dataikudss_docker_build_base_image_mode == "build")
    and ((result_test_container_exec_docker_image.images | length < 1) or docker_base_image_build_script.changed)
