---
name: Molecule Test
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install --upgrade ansible==6.7.0 yamllint ansible-lint
      - name: Ansible Lint
        run: |
          ansible-galaxy install -r requirements.yml
          ansible-lint -x package-latest
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        platform: [ 'molecule-debian10', 'molecule-centos7', 'molecule-centos8' ]
      # When set to true, GitHub cancels all in-progress jobs if any matrix job fails.
      fail-fast: true
      # The maximum number of jobs that can run simultaneously
      max-parallel: 1
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v6
        with:
          root-reserve-mb: 4096
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install --upgrade ansible==5.9.0 molecule molecule-docker jmespath
      - name: Write license file without logging its content
        run: 'echo "$LICENSE" > license.json'
        shell: bash
        env:
          LICENSE: ${{ secrets.LICENSE }}
      - name: Test with molecule
        run: |
          ansible-galaxy install weareinteractive.docker
          ansible-galaxy install -r requirements.yml
          molecule test --platform-name=${{ matrix.platform }} --destroy=always
